name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Composer
        run: |
          composer validate
          composer install --no-interaction --prefer-dist

      - name: PHPStan
        run: |
          vendor/bin/phpstan analyse -c config/phpstan.neon --memory-limit 2048M
