version: "3.8"

services:

  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: snyt
      MYSQL_USER: snyt
      MYSQL_PASSWORD: snyt
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    environment:
      ADMINER_USERNAME: snyt
      ADMINER_PASSWORD: snyt
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "80:80"
