version: "3.8"

services:

  php:
    build:
      dockerfile: php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "80:80"

  node:
    build:
      dockerfile: node/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    command: [ "tail", "-f", "/dev/null" ]

  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: snyt
      MYSQL_USER: snyt
      MYSQL_PASSWORD: snyt
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    environment:
      ADMINER_USERNAME: snyt
      ADMINER_PASSWORD: snyt
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "1000:8080"
    depends_on:
      - mysql
